name: hello-
base: core20
version: '0.1'
summary: Snapcraft hello world
description: |
  Simple hello world snap.

grade: stable 
confinement: strict

apps:
  hello:
    command: hello.sh

parts:
  hello:
    source: hello
    plugin: dump
